### ISSUE TITLE
aggregate part locations by catalog number

### ISSUE THREAD

**Issue by ekrimmel** [ChicagoAcademyofSciences/arctos-reports#1]
Improve CHAS_PartStorageLoc by grouping parts with the same catalog number. Currently if parts are in different locations they will show up sorted by part location.

**Comment by ekrimmel** [comment]
in [CHAS_PartStorageLoc_2](../blob/master/CHAS_PartStorageLoc_2.sql) and  [CHAS_PartStorageLoc](../blob/master/CHAS_PartStorageLoc.sql)

**Comment by anna-chinn** [comment]
Done. [SQL handler](https://github.com/ChicagoAcademyofSciences/arctos-reports/blob/master/CHAS_PartStorageLoc.sql) updated for both [CHAS_PartStorageLoc_2](https://github.com/ChicagoAcademyofSciences/arctos-reports/blob/master/CHAS_PartStorageLoc_2.cfr) and [CHAS_PartStorageLoc](https://github.com/ChicagoAcademyofSciences/arctos-reports/blob/master/CHAS_PartStorageLoc.cfr).

Specimens group by alphabetically by family, then species, then numerically by catalogue number.
