### ISSUE TITLE
fix formatting on loan header report

### ISSUE THREAD

**Issue by ekrimmel** [ChicagoAcademyofSciences/arctos-reports#4]
Report _CHAS_loan_header_ is wonky. Some fields that should pull data in do not. Re-evaluate handler.

**Comment by ekrimmel** [comment]
in  [CHAS_loan_header.sql](../blob/master/CHAS_loan_header.sql)

**Comment by ekrimmel** [comment]
Also would be nice to embed the logo in the header

**Comment by anna-chinn** [comment]
Successfully attached logo to header:
Insert an image in ColdFusion Report Builder and paste the desired image path (should be a stable URL) into the image's expression builder.

Add the logo image to CHAS TACC media once permissions are straightened out.

**Comment by anna-chinn** [comment]
Done.
